### ISSUE TITLE
10.4: Could not solve for environment specs (ecl)

### ISSUE THREAD

**Issue by hgustafsson** [conda-forge/sage-feedstock#103]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

I'm not able to install sage 10.4 from conda-forge.

```mamba create -n sage sage=10.4``` gives

```
Could not solve for environment specs
The following package could not be installed
└─ sage 10.4**  is not installable because it requires
   ├─ ecl >=24.5.10,<25 , which can be installed;
   └─ maxima >=5.46.0,<6 , which requires
      └─ ecl >=23.9.9,<23.9.10.0a0 , which conflicts with any installable versions previously reported.
```

I'm on macos 14.4.1 and have just made a fresh install of miniforge via homebrew.
The latest version of sage that I can install using for example ```mamba create -n sage sage``` is version 10.0. There are similar dependency issues for 10.1-10.3.

```mamba search sage``` gives

```
Loading channels: done
# Name                       Version           Build  Channel             
sage                             9.2  py38h150bfb4_1  conda-forge         
sage                             9.2  py39hdf13c20_1  conda-forge         
sage                             9.3      hd8ed1ab_0  conda-forge         
sage                             9.3      hd8ed1ab_1  conda-forge         
sage                             9.4      hd8ed1ab_0  conda-forge         
sage                             9.5      hd8ed1ab_0  conda-forge         
sage                             9.5      hd8ed1ab_1  conda-forge         
sage                             9.5      hd8ed1ab_2  conda-forge         
sage                             9.6      hd8ed1ab_0  conda-forge         
sage                             9.7      hd8ed1ab_0  conda-forge         
sage                             9.8      hd8ed1ab_0  conda-forge         
sage                            10.0      hd8ed1ab_0  conda-forge         
sage                            10.1      hd8ed1ab_0  conda-forge         
sage                            10.2      hd8ed1ab_0  conda-forge         
sage                            10.3      hd8ed1ab_0  conda-forge         
sage                            10.4      hd8ed1ab_0  conda-forge
```

### Installed packages

-

### Environment info

```
     active environment : base
    active env location : /opt/homebrew/Caskroom/miniforge/base
            shell level : 1
       user config file : /Users/$USER/.condarc
 populated config files : /opt/homebrew/Caskroom/miniforge/base/.condarc
                          /Users/$USER/.condarc
          conda version : 24.9.2
    conda-build version : not installed
         python version : 3.12.6.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m2
                          __conda=24.9.2=0
                          __osx=14.4.1=0
                          __unix=0=0
       base environment : /opt/homebrew/Caskroom/miniforge/base  (writable)
      conda av data dir : /opt/homebrew/Caskroom/miniforge/base/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/homebrew/Caskroom/miniforge/base/pkgs
                          /Users/$USER/.conda/pkgs
       envs directories : /opt/homebrew/Caskroom/miniforge/base/envs
                          /Users/$USER/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.9.2 requests/2.32.3 CPython/3.12.6 Darwin/23.4.0 OSX/14.4.1 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.10
                UID:GID : ###
             netrc file : None
           offline mode : False
```

**Comment by linuxmetel** [comment]
I have the same trouble.

**Comment by saraedum** [comment]
maxima 5.46 was indeed not build for Silicon macOS. The latest 5.47 is available on that platform. I believe that this issue is therefore resolved. Could you check again @linuxmetel @hgustafsson ?

**Comment by hgustafsson** [comment]
Thanks for looking into it!
I get the same error message as before when trying to install sage=10.4 (see above)

If I try to install only maxima=5.47 and ecl=24.5.10 (which is the lowest version required by sage 10.4) I get the message:
```
Could not solve for environment specs
The following packages are incompatible
├─ ecl 24.5.10**  is requested and can be installed;
└─ maxima 5.47**  is not installable because it requires
   └─ ecl >=23.9.9,<23.9.10.0a0 , which conflicts with any installable versions previously reported.
```

**Comment by saraedum** [comment]
Indeed, it seems there was some trouble on Silicon https://github.com/conda-forge/maxima-feedstock/pull/27 that's why @isuruf removed it it seems.

Can you try to install the osx-64 (i.e., rosetta) version?

**Comment by GZTimeWalker** [comment]
Maybe we should ask @isuruf to rebuild a package with depends upgrade like what he done in https://github.com/conda-forge/maxima-feedstock/issues/35

latest package `_3`: `__osx >=10.13, ecl >=24.5.10,<24.5.11.0a0, gmp >=6.3.0,<7.0a0, readline >=8.2,<9.0a0`
the last arm64 package `_2`: `ecl >=23.9.9,<23.9.10.0a0, gmp >=6.3.0,<7.0a0, readline >=8.2,<9.0a0`

**Comment by GZTimeWalker** [comment]
As maxima has been updated, the next problem seems to be `arb` package:

```
error    libmamba Could not solve for environment specs
    The following packages are incompatible
    ├─ python =3.12 * is installable with the potential options
    │  ├─ python [3.12.0|3.12.1|...|3.12.9] would require
    │  │  └─ python_abi =3.12 *_cp312, which can be installed;
    │  └─ python 3.12.0rc3 would require
    │     └─ _python_rc =* *, which does not exist (perhaps a missing channel);
    └─ sage =10.5 * is installable and it requires
       ├─ arb =* * with the potential options
       │  ├─ arb [2.19.0|2.20.0] would require
       │  │  └─ libflint >=2.7.1,<2.8.0a0 *, which can be installed;
       │  ├─ arb [2.20.0|2.21.1] would require
       │  │  └─ libflint >=2.8.0,<2.9.0a0 *, which can be installed;
       │  ├─ arb [2.22.1|2.23.0] would require
       │  │  └─ libflint >=2.9.0,<2.10.0a0 *, which can be installed;
       │  └─ arb 2.22.1 would require
       │     └─ libflint >=2.8.4,<2.9.0a0 *, which can be installed;
       └─ sagelib =10.5 * with the potential options
          ├─ sagelib 10.5 would require
          │  └─ python_abi =3.10 *_cp310, which conflicts with any installable versions previously reported;
          ├─ sagelib 10.5 would require
          │  └─ python_abi =3.11 *_cp311, which conflicts with any installable versions previously reported;
          ├─ sagelib 10.5 would require
          │  └─ libflint [=* *_ntl_*|>=3.0.1,<3.1.0a0 *] with the potential options
          │     ├─ libflint [3.0.0|3.0.1|3.1.2] conflicts with any installable versions previously reported;
          │     ├─ libflint 2.7.1, which can be installed;
          │     ├─ libflint 2.8.0, which can be installed;
          │     ├─ libflint 2.8.4, which can be installed;
          │     ├─ libflint 2.9.0, which can be installed;
          │     └─ libflint 3.0.1 conflicts with any installable versions previously reported;
          └─ sagelib 10.5 would require
             └─ python_abi =3.9 *_cp39, which conflicts with any installable versions previously reported.
critical libmamba Could not solve for environment specs
```

where `sagelib` need `libflint [=* *_ntl_*|>=3.0.1,<3.1.0a0 *]` but no `arb` version is matched.

**Comment by GZTimeWalker** [comment]
cc @saraedum , I see your comment in this pr: https://github.com/conda-forge/arb-feedstock/pull/35

If arb is already a part of libflint, should it be removed from sage's dependencies, and I'm not sure if there are any more dependency issues.

**Comment by saraedum** [comment]
@isuruf, the flint pin here seems to be wrong. It should not allow a non-3 flint but it does, right?

```
          ├─ sagelib 10.5 would require
          │  └─ libflint [=* *_ntl_*|>=3.0.1,<3.1.0a0 *] with the potential options
          │     ├─ libflint [3.0.0|3.0.1|3.1.2] conflicts with any installable versions previously reported;
          │     ├─ libflint 2.7.1, which can be installed;
          │     ├─ libflint 2.8.0, which can be installed;
          │     ├─ libflint 2.8.4, which can be installed;
          │     ├─ libflint 2.9.0, which can be installed;
          │     └─ libflint 3.0.1 conflicts with any installable versions previously reported;
```

I guess https://github.com/conda-forge/sagelib-feedstock/blob/main/recipe/meta.yaml#L76 doesn't do what we wanted it to do anymore.

**Comment by saraedum** [comment]
@GZTimeWalker can you try to install sagelib instead of sage on your machine? That should work now. Otherwise, we're missing some packages still.

**Comment by GZTimeWalker** [comment]
> @GZTimeWalker can you try to install sagelib instead of sage on your machine? That should work now. Otherwise, we're missing some packages still.
> 
> And if you feel like it you could try to add everything but `arb` from the `run:` list here to that environment and see if you run into any further issues: [`main`/recipe/meta.yaml#L13](https://github.com/conda-forge/sage-feedstock/blob/main/recipe/meta.yaml#L13)

I tried, the command:

```sh
mamba create -n sage sagelib=10.5 python=3.12
```

everything is okay, final outputs:

```txt
Summary:

  Install: 139 packages

  Total download: 453MB
```

for other packages in `meta.yaml`, let me try.

**Comment by GZTimeWalker** [comment]
@saraedum I have tested all dependencies  in the current meta.yaml, the result is if I removed `arb`, everything looks okay, mamba will accept the config:

```txt
  Summary:

  Install: 366 packages

  Total download: 1GB
```

the test config:

```
name: sage
channels:
  - conda-forge
dependencies:
  - python=3.12
  - sagelib=10.5

  - alabaster >=0.7.16
  # - arb
  - babel >=2.14.0,<3
  - bdw-gc >=8.0.4,<9
  - blas-devel
  - bleach >=6.1.0,<7
  - brial
  - cddlib >=1!0.94m
  - certifi
  - cliquer
  - conway-polynomials >=0.10
  - cvxopt >=1.3.2,<2
  - cycler >=0.11.0
  - cypari2
  - cysignals
  - cython >=3,<4
  - decorator >=5.1.1,<6
  - docutils >=0.20.1
  - ecl >=24.5.10,<25
  - eclib
  - ecm
  - entrypoints >=0.4
  - fflas-ffpack >=2.5.0
  - flintqs >=1.0,<2
  - fplll >=5.4.5,<6
  - fpylll >=0.6.0
  - freetype >=2.10.4,<3
  - gap-defaults >=4.12.2
  - gf2x >=1.3,<2
  - gfan >=0.6.2
  - giac >=1.9.0.15,<2
  - givaro >=4.1.1,<5
  - glpk
  - gmp
  - gmpy2
  - gsl
  - iml
  - ipykernel >=6.6.0,<7
  - ipython >=8.18.1,<9
  - ipywidgets >=8.1.1,<9
  - jinja2
  - jmol >=14.29.52,<15
  - jsonschema >=4.17.3,<5
  - jupyter_client >=8.3.1,<9
  - jupyter_core >=5.3.2,<6
  - lcalc
  - libbraiding
  - libflint
  - libgd
  - libhomfly
  - libiconv >=1.15,<2
  - libpng
  - linbox >=1.7.0
  - lrcalc >=2.1,<3
  - m4ri
  - m4rie
  - matplotlib-base >=3.8.0,<4
  - maxima >=5.46.0,<6
  - mistune >=2.0.4
  - mpc
  - mpfi
  - mpfr
  - mpmath >=1.3.0,<2
  - nauty >=2.8.8,<3
  - nbclient >=0.8.0,<0.9
  - nbconvert >=7.9.2,<8
  - nbformat >=5.9.2,<6
  - ncurses >=6.3,<7
  - networkx >=3.2.1,<4
  - notebook >=7.1.1,<8
  - ntl
  - numpy
  - palp >=2.11,<3
  - pari >=2.15.4,<3
  - pexpect >=4.9.0,<5
  - pickleshare >=0.7.5,<1.0
  - pillow >=10.1.0,<11
  - pkg-config
  - pkgconfig
  - planarity
  - ppl
  - pplpy
  - primecountpy >=0.1.0,<0.2.0
  - ptyprocess >=0.7.0,<1
  - pygments >=2.18.0,<3
  - pyparsing >=3.1.1,<4
  - python >=3.9
  - python-dateutil >=2.9.0,<3
  - pythran >=0.14.0,<0.15
  - pytz >=2023.3.post1
  - pyzmq >=25.1.1,<26
  - readline
  - rpy2 >=3.4.5,<4
  - rubiks >=20070912
  - rw
  - sagemath-db-combinatorial-designs >=20140630
  - sagemath-db-elliptic-curves >=0.8.1
  - sagemath-db-graphs >=20210214
  - sagemath-db-polytopes >=20170220
  - sagetex >=3.6.1,<4
  - scipy >=1.12.0,<2
  - simplegeneric >=0.8.1,<1

  - singular
  - six >=1.16.0,<2
  - sphinx >=7.2.6,<8
  - sqlite >=3.36,<4
  - symmetrica
  - sympow >=2.023.6,<3
  - sympy >=1.12.1,<2
  - tachyon 0.99.*
  - terminado >=0.17.1
  - three.js 122
  - tornado >=6.4,<7
  - traitlets >=5.14.3,<6
  - wcwidth >=0.2.12,<2
  - widgetsnbextension >=4.0.9,<5
  - zeromq >=4.3.5,<5
  - zlib
  - zn_poly

  - pip
```

If I create the PR, the only thing I need do is to remove the `arb`?

**Comment by GZTimeWalker** [comment]
Hey there, I tried to use the latest package, and I got an error when try to use `from sage.all import *`:

```txt
>>> from sage.all import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "envs/sage/lib/python3.12/site-packages/sage/all.py", line 93, in <module>
    from sage.algebras.all import *
  File "envs/sage/lib/python3.12/site-packages/sage/algebras/all.py", line 25, in <module>
    from sage.algebras.quatalg.all import *
  File "envs/sage/lib/python3.12/site-packages/sage/algebras/quatalg/all.py", line 1, in <module>
    from sage.algebras.quatalg.quaternion_algebra import QuaternionAlgebra
  File "envs/sage/lib/python3.12/site-packages/sage/algebras/quatalg/quaternion_algebra.py", line 76, in <module>
    from . import quaternion_algebra_cython
  File "sage/algebras/quatalg/quaternion_algebra_cython.pyx", line 1, in init sage.algebras.quatalg.quaternion_algebra_cython (build/cythonized/sage/algebras/quatalg/quaternion_algebra_cython.cpp:7958)
  File "sage/matrix/matrix_integer_dense.pyx", line 1, in init sage.matrix.matrix_integer_dense (build/cythonized/sage/matrix/matrix_integer_dense.cpp:68772)
ImportError: dlopen(envs/sage/lib/python3.12/site-packages/sage/libs/linbox/linbox_flint_interface.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '__ZN6FFPACK8CharPolyIN6Givaro8Poly1DomINS1_7ModularIddvEENS1_5DenseEEEEERNT_7ElementERKS7_S9_mNS7_8Domain_t11Element_ptrEmRNS7_8Domain_t8RandIterENS_19FFPACK_CHARPOLY_TAGEm'
```

It looks like an error with `libflint`, so I give it back to here, and I'm waiting for the remote channel to update to the latest build.

**Comment by saraedum** [comment]
Could you create a new issue please with the installed packages? Hard to say what's happening exactly without the full list of packages.
