### ISSUE TITLE
Package for aarch64 architecture is currently broken

### ISSUE THREAD

**Issue by fantognazza** [conda-forge/sage-feedstock#81]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I was building a CI container image for both `x86_64` and `aarch64` architectures installing sage from micromamba as suggested by the documentation, and I realized that the same image was not working for the ARM architecture.

```
[user@host]~% podman run -it --rm localhost/test_image /bin/bash
root@d65e0a177de4:/# source /root/.bashrc
root@d65e0a177de4:/# micromamba activate base
(base) root@d65e0a177de4:/# sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 9.7, Release Date: 2022-09-19                     │
│ Using Python 3.10.8. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Warning: sage.all is not available; this is a limited REPL.        ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Traceback (most recent call last):
  File "/root/micromamba/bin/sage-ipython", line 12, in <module>
    from sage.repl.interpreter import SageTerminalApp
  File "/root/micromamba/lib/python3.10/site-packages/sage/repl/interpreter.py", line 144, in <module>
    from sage.repl.preparse import preparse, containing_block
  File "/root/micromamba/lib/python3.10/site-packages/sage/repl/preparse.py", line 245, in <module>
    from sage.repl.load import load_wrap
  File "/root/micromamba/lib/python3.10/site-packages/sage/repl/load.py", line 16, in <module>
    from sage.cpython.string import str_to_bytes, bytes_to_str, FS_ENCODING
ModuleNotFoundError: No module named 'sage.cpython.string'
```

I paste here a minimal Dockerfile to reproduce the error, which can be generated with `podman build . -t test_image`:
```
FROM docker.io/debian:latest

USER root

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
       apt-get install --no-install-recommends -y \
                        ca-certificates \
                        curl \
                        bzip2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN "${SHELL}" <(curl -L micro.mamba.pm/install.sh)

RUN bash -c "source /root/.bashrc ; micromamba install -y -n base -c conda-forge sage \
    && micromamba clean --all --yes"
```

I already tested:

- different base images (Ubuntu jammy, Fedora 37)
- directly using the [micromamba docker image](https://hub.docker.com/r/mambaorg/micromamba)
- use the environment file with the same packages and versions of the x86_64 working image

By contrast, the sagemath package distributed through Debian repository is working fine.

Please note that:

- the error is present only on aarch64 ARM architecture (I am using an Oracle Ampere A1 instance)
- `podman` is a drop-in replacement to `docker` command (within this context)

### Installed packages

```shell
List of packages in environment: "/root/micromamba"

  Name                               Version       Build                     Channel
──────────────────────────────────────────────────────────────────────────────────────────
  _ipython_minor_entry_point         8.7.0         hb6b4a82_0                conda-forge
  _openmp_mutex                      4.5           2_gnu                     conda-forge
  _r-mutex                           1.0.1         anacondar_1               conda-forge
  alabaster                          0.7.12        py_0                      conda-forge
  alsa-lib                           1.2.8         h4e544f5_0                conda-forge
  anyio                              3.6.2         pyhd8ed1ab_0              conda-forge
  arb                                2.23.0        h37d5dab_0                conda-forge
  argon2-cffi                        21.3.0        pyhd8ed1ab_0              conda-forge
  argon2-cffi-bindings               21.2.0        py310h761cc84_3           conda-forge
  arpack                             3.7.0         hf862f49_2                conda-forge
  asttokens                          2.2.1         pyhd8ed1ab_0              conda-forge
  attrs                              22.1.0        pyh71513ae_1              conda-forge
  babel                              2.11.0        pyhd8ed1ab_0              conda-forge
  backcall                           0.2.0         pyh9f0ad1d_0              conda-forge
  backports                          1.0           pyhd8ed1ab_3              conda-forge
  backports.functools_lru_cache      1.6.4         pyhd8ed1ab_0              conda-forge
  bdw-gc                             8.0.6         hd62202e_0                conda-forge
  beautifulsoup4                     4.11.1        pyha770c72_0              conda-forge
  beniget                            0.4.1         pyhd8ed1ab_0              conda-forge
  binutils_impl_linux-aarch64        2.39          h48546ad_1                conda-forge
  binutils_linux-aarch64             2.39          h489c705_11               conda-forge
  blas-devel                         3.9.0         16_linuxaarch64_openblas  conda-forge
  bleach                             4.1.0         pyhd8ed1ab_0              conda-forge
  brial                              1.2.11        pyh694c41f_0              conda-forge
  brotli                             1.0.9         h4e544f5_8                conda-forge
  brotli-bin                         1.0.9         h4e544f5_8                conda-forge
  brotlipy                           0.7.0         py310h761cc84_1005        conda-forge
  bwidget                            1.9.14        h8af1aa0_1                conda-forge
  bzip2                              1.0.8         hf897c2e_4                conda-forge
  c-ares                             1.18.1        hf897c2e_0                conda-forge
  ca-certificates                    2022.12.7     h4fd8a4c_0                conda-forge
  cairo                              1.16.0        hd19fb6e_1014             conda-forge
  cddlib                             1!0.94m       h719063d_0                conda-forge
  certifi                            2022.12.7     pyhd8ed1ab_0              conda-forge
  cffi                               1.15.1        py310hf0c4615_2           conda-forge
  charset-normalizer                 2.1.1         pyhd8ed1ab_0              conda-forge
  cliquer                            1.22          hb9de7d4_0                conda-forge
  colorama                           0.4.6         pyhd8ed1ab_0              conda-forge
  comm                               0.1.1         pyhd8ed1ab_0              conda-forge
  contourpy                          1.0.6         py310hb15e014_0           conda-forge
  cryptography                       38.0.4        py310h674ca28_0           conda-forge
  curl                               7.86.0        h22f3f83_1                conda-forge
  cvxopt                             1.3.0         py310haa23bb0_4           conda-forge
  cycler                             0.11.0        pyhd8ed1ab_0              conda-forge
  cypari2                            2.1.3         py310h0792cfb_0           conda-forge
  cysignals                          1.11.2        py310h87d4683_0           conda-forge
  cython                             0.29.32       py310h130cc07_1           conda-forge
  debugpy                            1.6.4         py310h130cc07_0           conda-forge
  decorator                          5.1.1         pyhd8ed1ab_0              conda-forge
  defusedxml                         0.7.1         pyhd8ed1ab_0              conda-forge
  docutils                           0.17.1        py310hbbe02a8_3           conda-forge
  dsdp                               5.8           hb12102e_1203             conda-forge
  ecl                                21.2.1        haa44c19_2                conda-forge
  eclib                              20220621      h87efab1_1                conda-forge
  ecm                                7.0.4         h719063d_1002             conda-forge
  entrypoints                        0.4           pyhd8ed1ab_0              conda-forge
  executing                          1.2.0         pyhd8ed1ab_0              conda-forge
  expat                              2.5.0         ha18d298_0                conda-forge
  fflas-ffpack                       2.4.3         hf104d39_2                conda-forge
  fftw                               3.3.10        nompi_ha1d0423_106        conda-forge
  flintqs                            1.0           h5fb5790_1001             conda-forge
  flit-core                          3.8.0         pyhd8ed1ab_0              conda-forge
  font-ttf-dejavu-sans-mono          2.37          hab24e00_0                conda-forge
  font-ttf-inconsolata               3.000         h77eed37_0                conda-forge
  font-ttf-source-code-pro           2.038         h77eed37_0                conda-forge
  font-ttf-ubuntu                    0.83          hab24e00_0                conda-forge
  fontconfig                         2.14.1        h77febde_0                conda-forge
  fonts-conda-ecosystem              1             0                         conda-forge
  fonts-conda-forge                  1             0                         conda-forge
  fonttools                          4.38.0        py310h761cc84_1           conda-forge
  fplll                              5.4.2         h6512c63_1                conda-forge
  fpylll                             0.5.7         py310h08e7b9e_1           conda-forge
  freetype                           2.12.1        hbbbf32d_1                conda-forge
  fribidi                            1.0.10        hb9de7d4_0                conda-forge
  future                             0.18.2        pyhd8ed1ab_6              conda-forge
  gap-core                           4.11.1        h7637c83_4                conda-forge
  gap-defaults                       4.11.1        h8af1aa0_4                conda-forge
  gast                               0.5.3         pyhd8ed1ab_0              conda-forge
  gcc_impl_linux-aarch64             10.4.0        h9569200_19               conda-forge
  gcc_linux-aarch64                  10.4.0        h72ad2ee_11               conda-forge
  gettext                            0.21.1        ha18d298_0                conda-forge
  gf2x                               1.3.0         h1b3b3a3_2                conda-forge
  gfan                               0.6.2         h5f589ec_1003             conda-forge
  gfortran_impl_linux-aarch64        10.4.0        hf5786aa_19               conda-forge
  giac                               1.9.0.21      h8f6a60c_0                conda-forge
  giflib                             5.2.1         hb9de7d4_2                conda-forge
  givaro                             4.1.1         h192cbe9_1                conda-forge
  glpk                               5.0           h66325d0_0                conda-forge
  gmp                                6.2.1         h7fd3ca4_0                conda-forge
  gmpy2                              2.1.2         py310h9f74ea4_1           conda-forge
  graphite2                          1.3.13        h7fd3ca4_1001             conda-forge
  gsl                                2.7           h294027d_0                conda-forge
  gxx_impl_linux-aarch64             10.4.0        h9569200_19               conda-forge
  gxx_linux-aarch64                  10.4.0        hb08d869_11               conda-forge
  harfbuzz                           5.3.0         h6f3452c_0                conda-forge
  icu                                70.1          ha18d298_0                conda-forge
  idna                               3.4           pyhd8ed1ab_0              conda-forge
  igraph                             0.9.10        hefb87a8_1                conda-forge
  imagesize                          1.4.1         pyhd8ed1ab_0              conda-forge
  iml                                1.0.5         h9076c59_1003             conda-forge
  importlib-metadata                 5.1.0         pyha770c72_0              conda-forge
  importlib_resources                5.10.1        pyhd8ed1ab_0              conda-forge
  ipykernel                          6.19.1        pyh210e3f2_0              conda-forge
  ipython                            8.7.0         pyh41d4057_0              conda-forge
  ipython_genutils                   0.2.0         py_1                      conda-forge
  ipywidgets                         7.7.2         pyhd8ed1ab_0              conda-forge
  jedi                               0.18.2        pyhd8ed1ab_0              conda-forge
  jinja2                             3.1.2         pyhd8ed1ab_1              conda-forge
  jmol                               14.32.10      h8af1aa0_0                conda-forge
  jpeg                               9e            h9cdd2b7_2                conda-forge
  jsonschema                         4.17.3        pyhd8ed1ab_0              conda-forge
  jupyter_client                     7.4.8         pyhd8ed1ab_0              conda-forge
  jupyter_core                       4.12.0        py310h4c7bcd0_0           conda-forge
  jupyter_server                     1.23.3        pyhd8ed1ab_0              conda-forge
  jupyterlab_pygments                0.2.2         pyhd8ed1ab_0              conda-forge
  jupyterlab_widgets                 1.1.1         pyhd8ed1ab_0              conda-forge
  kernel-headers_linux-aarch64       4.18.0        h5b4a56d_13               conda-forge
  keyutils                           1.6.1         h4e544f5_0                conda-forge
  kiwisolver                         1.4.4         py310h9ceb0a0_1           conda-forge
  krb5                               1.19.3        h750e270_0                conda-forge
  lcalc                              2.0.5         h4e3e9a1_0                conda-forge
  lcms2                              2.14          h5246980_0                conda-forge
  ld_impl_linux-aarch64              2.39          h16cd69b_1                conda-forge
  lerc                               4.0.0         h4de3ea5_0                conda-forge
  libblas                            3.9.0         16_linuxaarch64_openblas  conda-forge
  libbraiding                        1.1           h7fd3ca4_0                conda-forge
  libbrial                           1.2.11        h90c5a80_0                conda-forge
  libbrotlicommon                    1.0.9         h4e544f5_8                conda-forge
  libbrotlidec                       1.0.9         h4e544f5_8                conda-forge
  libbrotlienc                       1.0.9         h4e544f5_8                conda-forge
  libcblas                           3.9.0         16_linuxaarch64_openblas  conda-forge
  libcups                            2.3.3         h0c1ea75_2                conda-forge
  libcurl                            7.86.0        h22f3f83_1                conda-forge
  libdeflate                         1.14          h4e544f5_0                conda-forge
  libedit                            3.1.20191231  he28a2e2_2                conda-forge
  libev                              4.33          h516909a_1                conda-forge
  libffi                             3.4.2         h3557bc0_5                conda-forge
  libflint                           2.9.0         hd3470fa_ntl_100          conda-forge
  libgcc-devel_linux-aarch64         10.4.0        h3c6860a_19               conda-forge
  libgcc-ng                          12.2.0        h607ecd0_19               conda-forge
  libgd                              2.3.3         h1aa4b80_3                conda-forge
  libgfortran-ng                     12.2.0        he9431aa_19               conda-forge
  libgfortran5                       12.2.0        hf695500_19               conda-forge
  libglib                            2.74.1        h01e6fbd_1                conda-forge
  libgomp                            12.2.0        h607ecd0_19               conda-forge
  libhomfly                          1.02r6        hb9de7d4_0                conda-forge
  libhwloc                           2.8.0         hc0facba_1                conda-forge
  libiconv                           1.17          h9cdd2b7_0                conda-forge
  liblapack                          3.9.0         16_linuxaarch64_openblas  conda-forge
  liblapacke                         3.9.0         16_linuxaarch64_openblas  conda-forge
  libnghttp2                         1.47.0        h674c3cc_1                conda-forge
  libnsl                             2.0.0         hf897c2e_0                conda-forge
  libopenblas                        0.3.21        pthreads_h6cb6f83_3       conda-forge
  libpng                             1.6.39        hf9034f9_0                conda-forge
  libsanitizer                       10.4.0        h0e20637_19               conda-forge
  libsodium                          1.0.18        hb9de7d4_1                conda-forge
  libsqlite                          3.40.0        hf9034f9_0                conda-forge
  libssh2                            1.10.0        he5a64b1_3                conda-forge
  libstdcxx-devel_linux-aarch64      10.4.0        h3c6860a_19               conda-forge
  libstdcxx-ng                       12.2.0        hc13a102_19               conda-forge
  libtiff                            4.4.0         hacef7f3_4                conda-forge
  libuuid                            2.32.1        hf897c2e_1000             conda-forge
  libwebp                            1.2.4         hef792ef_0                conda-forge
  libwebp-base                       1.2.4         h4e544f5_0                conda-forge
  libxcb                             1.13          h3557bc0_1004             conda-forge
  libxml2                            2.10.3        h249b6dd_0                conda-forge
  libxslt                            1.1.37        h4871090_0                conda-forge
  libzlib                            1.2.13        h4e544f5_4                conda-forge
  linbox                             1.6.3         h31716a8_7                conda-forge
  lrcalc                             2.1           h4de3ea5_4                conda-forge
  lxml                               4.9.1         py310h141c14b_1           conda-forge
  m4ri                               20140914      h75e8696_1005             conda-forge
  m4rie                              20150908      h75e8696_1001             conda-forge
  make                               4.3           h309ac5b_1                conda-forge
  markupsafe                         2.1.1         py310hdc54845_2           conda-forge
  matplotlib-base                    3.6.2         py310hf92b850_0           conda-forge
  matplotlib-inline                  0.1.6         pyhd8ed1ab_0              conda-forge
  maxima                             5.45.0        haa44c19_3                conda-forge
  memory-allocator                   0.1.2         py310h761cc84_2           conda-forge
  metis                              5.1.0         h7fd3ca4_1006             conda-forge
  mistune                            0.8.4         py310h7cee911_1005        conda-forge
  mpc                                1.2.1         h846f343_0                conda-forge
  mpfi                               1.5.4         h846f343_1001             conda-forge
  mpfr                               4.1.0         h719063d_1                conda-forge
  mpmath                             1.2.1         pyhd8ed1ab_0              conda-forge
  munkres                            1.1.4         pyh9f0ad1d_0              conda-forge
  nauty                              2.7.2         hf897c2e_0                conda-forge
  nbclassic                          0.4.8         pyhd8ed1ab_0              conda-forge
  nbclient                           0.6.8         pyhd8ed1ab_0              conda-forge
  nbconvert                          6.5.3         pyhd8ed1ab_0              conda-forge
  nbconvert-core                     6.5.3         pyhd8ed1ab_0              conda-forge
  nbconvert-pandoc                   6.5.3         pyhd8ed1ab_0              conda-forge
  nbformat                           5.7.0         pyhd8ed1ab_0              conda-forge
  ncurses                            6.3           headf329_1                conda-forge
  nest-asyncio                       1.5.6         pyhd8ed1ab_0              conda-forge
  networkx                           2.8.8         pyhd8ed1ab_0              conda-forge
  notebook                           6.5.2         pyha770c72_1              conda-forge
  notebook-shim                      0.2.2         pyhd8ed1ab_0              conda-forge
  ntl                                11.4.3        h0d7519b_1                conda-forge
  numpy                              1.23.5        py310he617cf3_0           conda-forge
  openblas                           0.3.21        pthreads_h2d9dd7e_3       conda-forge
  openjdk                            17.0.3        h5ee6981_4                conda-forge
  openjpeg                           2.5.0         h9b6de37_1                conda-forge
  openssl                            3.0.7         hb4cce97_1                conda-forge
  packaging                          21.3          pyhd8ed1ab_0              conda-forge
  palp                               2.20          hb9de7d4_0                conda-forge
  pandoc                             2.19.2        h8af1aa0_1                conda-forge
  pandocfilters                      1.5.0         pyhd8ed1ab_0              conda-forge
  pango                              1.50.12       h3f2bcdb_0                conda-forge
  pari                               2.13.3        h05482ea_1_pthread        conda-forge
  pari-galdata                       0.0.20180411  0                         conda-forge
  pari-seadata-small                 0.0.20090618  0                         conda-forge
  parso                              0.8.3         pyhd8ed1ab_0              conda-forge
  pcre2                              10.40         he7b27c6_0                conda-forge
  perl                               5.32.1        2_hf897c2e_perl5          conda-forge
  pexpect                            4.8.0         pyh1a96a4e_2              conda-forge
  pickleshare                        0.7.5         py_1003                   conda-forge
  pillow                             9.2.0         py310hd6d4ca1_3           conda-forge
  pip                                22.3.1        pyhd8ed1ab_0              conda-forge
  pixman                             0.40.0        hb9de7d4_0                conda-forge
  pkg-config                         0.29.2        hb9de7d4_1008             conda-forge
  pkgconfig                          1.5.5         pyhd8ed1ab_4              conda-forge
  pkgutil-resolve-name               1.3.10        pyhd8ed1ab_0              conda-forge
  planarity                          3.0.0.5       hb9de7d4_1002             conda-forge
  ply                                3.11          py_1                      conda-forge
  ppl                                1.2           h984aac9_1006             conda-forge
  pplpy                              0.8.6         py310h5279ff7_1           conda-forge
  primecount                         7.4           hd600fc2_1                conda-forge
  primecountpy                       0.1.0         py310hb15e014_2           conda-forge
  primesieve                         8.0           h4de3ea5_0                conda-forge
  prometheus_client                  0.15.0        pyhd8ed1ab_0              conda-forge
  prompt-toolkit                     3.0.36        pyha770c72_0              conda-forge
  psutil                             5.9.4         py310h761cc84_0           conda-forge
  pthread-stubs                      0.4           hb9de7d4_1001             conda-forge
  ptyprocess                         0.7.0         pyhd3deb0d_0              conda-forge
  pure_eval                          0.2.2         pyhd8ed1ab_0              conda-forge
  pycparser                          2.21          pyhd8ed1ab_0              conda-forge
  pygments                           2.13.0        pyhd8ed1ab_0              conda-forge
  pyopenssl                          22.1.0        pyhd8ed1ab_0              conda-forge
  pyparsing                          3.0.9         pyhd8ed1ab_0              conda-forge
  pyrsistent                         0.19.2        py310hdc54845_0           conda-forge
  pysocks                            1.7.1         pyha2e5f31_6              conda-forge
  python                             3.10.8        hac3cb69_0_cpython        conda-forge
  python-dateutil                    2.8.2         pyhd8ed1ab_0              conda-forge
  python-fastjsonschema              2.16.2        pyhd8ed1ab_0              conda-forge
  python-lrcalc                      2.1           py310h130cc07_4           conda-forge
  python-tzdata                      2022.7        pyhd8ed1ab_0              conda-forge
  python_abi                         3.10          3_cp310                   conda-forge
  pythran                            0.11.0        py310hfd19f87_3           conda-forge
  pytz                               2022.6        pyhd8ed1ab_0              conda-forge
  pytz-deprecation-shim              0.1.0.post0   py310h4c7bcd0_3           conda-forge
  pyzmq                              23.2.1        py310h7c6bb8d_0           conda-forge
  qd                                 2.3.22        h05efe27_1004             conda-forge
  r-base                             4.2.2         h3f2eb09_1                conda-forge
  ratpoints                          2.1.3         h66325d0_1002             conda-forge
  readline                           8.1.2         h38e3740_0                conda-forge
  requests                           2.28.1        pyhd8ed1ab_1              conda-forge
  rpy2                               3.5.6         py310r42h7943a33_0        conda-forge
  rubiks                             20070912      h7fd3ca4_1001             conda-forge
  rw                                 0.9           hf897c2e_0                conda-forge
  sage                               9.7           hd8ed1ab_0                conda-forge
  sagelib                            9.7           py310h04a57a7_1           conda-forge
  sagemath-db-combinatorial-designs  20140630      1                         conda-forge
  sagemath-db-conway-polynomials     0.5.0         h4fd8a4c_1                conda-forge
  sagemath-db-elliptic-curves        0.8.1         hecc5488_0                conda-forge
  sagemath-db-graphs                 20210214      hd8ed1ab_0                conda-forge
  sagemath-db-polytopes              20170220      1                         conda-forge
  sagetex                            3.6.1         pyhd8ed1ab_0              conda-forge
  scipy                              1.9.3         py310hdd6f644_2           conda-forge
  sed                                4.8           ha0d5d3d_0                conda-forge
  send2trash                         1.8.0         pyhd8ed1ab_0              conda-forge
  setuptools                         65.5.1        pyhd8ed1ab_0              conda-forge
  simplegeneric                      0.8.1         py_1                      conda-forge
  singular                           4.2.1.p3      hc324b95_1                conda-forge
  six                                1.16.0        pyh6c4a22f_0              conda-forge
  sniffio                            1.3.0         pyhd8ed1ab_0              conda-forge
  snowballstemmer                    2.2.0         pyhd8ed1ab_0              conda-forge
  soupsieve                          2.3.2.post1   pyhd8ed1ab_0              conda-forge
  sphinx                             4.5.0         pyh6c4a22f_0              conda-forge
  sphinxcontrib-applehelp            1.0.2         py_0                      conda-forge
  sphinxcontrib-devhelp              1.0.2         py_0                      conda-forge
  sphinxcontrib-htmlhelp             2.0.0         pyhd8ed1ab_0              conda-forge
  sphinxcontrib-jsmath               1.0.1         py_0                      conda-forge
  sphinxcontrib-qthelp               1.0.3         py_0                      conda-forge
  sphinxcontrib-serializinghtml      1.1.5         pyhd8ed1ab_2              conda-forge
  sqlite                             3.40.0        h69ca7e5_0                conda-forge
  stack_data                         0.6.2         pyhd8ed1ab_0              conda-forge
  suitesparse                        5.10.1        h1404dd6_1                conda-forge
  symmetrica                         2.0           h7fd3ca4_1007             conda-forge
  sympow                             2.023.6       ha331e0d_2                conda-forge
  sympy                              1.11.1        py310h4c7bcd0_2           conda-forge
  sysroot_linux-aarch64              2.17          h43d7e78_13               conda-forge
  tachyon                            0.99b6        h63ab1d9_1001             conda-forge
  tbb                                2021.7.0      hdd96247_1                conda-forge
  terminado                          0.17.1        pyh41d4057_0              conda-forge
  three.js                           122           hd8ed1ab_2                conda-forge
  threejs-sage                       122           hd8ed1ab_2                conda-forge
  tinycss2                           1.2.1         pyhd8ed1ab_0              conda-forge
  tk                                 8.6.12        hd8af866_0                conda-forge
  tktable                            2.10          hcd05d48_3                conda-forge
  tornado                            6.2           py310hdc54845_1           conda-forge
  traitlets                          5.6.0         pyhd8ed1ab_0              conda-forge
  typing_extensions                  4.4.0         pyha770c72_0              conda-forge
  tzdata                             2022g         h191b570_0                conda-forge
  tzlocal                            4.2           py310h4c7bcd0_2           conda-forge
  unicodedata2                       15.0.0        py310h761cc84_0           conda-forge
  urllib3                            1.26.13       pyhd8ed1ab_0              conda-forge
  wcwidth                            0.2.5         pyh9f0ad1d_2              conda-forge
  webencodings                       0.5.1         py_1                      conda-forge
  websocket-client                   1.4.2         pyhd8ed1ab_0              conda-forge
  wheel                              0.38.4        pyhd8ed1ab_0              conda-forge
  widgetsnbextension                 3.6.1         pyha770c72_0              conda-forge
  xorg-fixesproto                    5.0           h3557bc0_1002             conda-forge
  xorg-inputproto                    2.3.2         h3557bc0_1002             conda-forge
  xorg-kbproto                       1.0.7         h3557bc0_1002             conda-forge
  xorg-libice                        1.0.10        h3557bc0_0                conda-forge
  xorg-libsm                         1.2.3         h965e137_1000             conda-forge
  xorg-libx11                        1.7.2         h3557bc0_0                conda-forge
  xorg-libxau                        1.0.9         h3557bc0_0                conda-forge
  xorg-libxdmcp                      1.1.3         h3557bc0_0                conda-forge
  xorg-libxext                       1.3.4         h3557bc0_1                conda-forge
  xorg-libxfixes                     5.0.3         h3557bc0_1004             conda-forge
  xorg-libxi                         1.7.10        h3557bc0_0                conda-forge
  xorg-libxrender                    0.9.10        h3557bc0_1003             conda-forge
  xorg-libxt                         1.2.1         h3557bc0_2                conda-forge
  xorg-libxtst                       1.2.3         hf897c2e_1002             conda-forge
  xorg-recordproto                   1.14.2        hf897c2e_1002             conda-forge
  xorg-renderproto                   0.11.1        h3557bc0_1002             conda-forge
  xorg-xextproto                     7.3.0         h3557bc0_1002             conda-forge
  xorg-xproto                        7.0.31        h3557bc0_1007             conda-forge
  xsimd                              8.0.5         hd62202e_0                conda-forge
  xz                                 5.2.6         h9cdd2b7_0                conda-forge
  zeromq                             4.3.4         h01db608_1                conda-forge
  zipp                               3.11.0        pyhd8ed1ab_0              conda-forge
  zlib                               1.2.13        h4e544f5_4                conda-forge
  zn_poly                            0.9.2         h719063d_0                conda-forge
  zstd                               1.5.2         hc1e27d5_4                conda-forge
```

### Environment info

```shell
__
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/


            environment : base (active)
           env location : /root/micromamba
      user config files : /root/.mambarc
 populated config files :
       libmamba version : 1.1.0
     micromamba version : 1.1.0
           curl version : libcurl/7.86.0 OpenSSL/1.1.1s zlib/1.2.13 libssh2/1.10.0 nghttp2/1.47.0
     libarchive version : libarchive 3.6.1 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       virtual packages : __unix=0=0
                          __linux=5.15.0=0
                          __glibc=2.31=0
                          __archspec=1=aarch64
               channels :
       base environment : /root/micromamba
               platform : linux-aarch64
```

**Comment by marcelroed** [comment]
Having the same issue on an M1 Mac.

**Comment by neldredge-unco** [comment]
Same issue on an aarch64 Raspberry Pi 4B running Arch Linux ARM.  

The Arch ARM port doesn't seem to have a sagemath package in its repository, so if conda doesn't work, then I guess I have to fall back to compiling from source.

**Comment by SHLEM666** [comment]
Same issue on aarch64 Raspberry Pi 3 (raspberry OS 64 lite). Trying with mamba and conda miniforge3.

**Comment by saraedum** [comment]
The installer conveniently deletes that file:
```
2024-01-08T05:58:09.9744104Z Cleaning up stale file: build/lib.linux-aarch64-cpython-311/sage/cpython/string.cpython-311-aarch64-linux-gnu.so
```

**Comment by saraedum** [comment]
On x86_64, this only deletes this single file:

```
Cleaning up stale file: $PREFIX/lib/python3.10/site-packages/sage/ext_data/nbconvert/__pycache__/postprocess.cpython-310.pyc
```

**Comment by saraedum** [comment]
I believe that this is still going to segfault. At least that's what it used to do on M1s a while back.

Or did you ever get this to work @alexjbest ?

**Comment by alexjbest** [comment]
Yeah I'm not sure I ever got it to work on an M1 confirmed

**Comment by saraedum** [comment]
Could you try (once build 4 of sagelib 10.2 is available, in a few hours) whether it works now?

**Comment by saraedum** [comment]
In docker I cannot install sage=10.2 because of a tachyon problem, see linked PR.

I'll try to install sagelib=10.2 build 4 once it shows up on the CDN.

**Comment by saraedum** [comment]
On aarch64, `sagelib` now seems to work:

```
(base) root@abd235f463ad:/# uname -m
aarch64
(base) root@abd235f463ad:/# sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.2, Release Date: 2023-12-03                    │
│ Using Python 3.11.8. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
sage: 1+1
2
```
