### ISSUE TITLE
Installation recommendation to use Python 3.9 not working with mambaforge

### ISSUE THREAD

**Issue by startakovsky** [conda-forge/sage-feedstock#86]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

python 3.9  and 3.8 doesn't come with libgap.... so I am getting an error even though on the official sage documentation they provide 3.9 as an example version of python. Am I missing something? `mamba create -n big-macs-llm sage python=3.9` installs sage without errors and I can import a number of things but when I try to import StandardTableaux I get an import name error referencing the libgap library. 

Any recommendations?

```
conda install libgap
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - libgap

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

### Installed packages

```shell
# Name                    Version                   Build  Channel
_r-mutex                  1.0.1               anacondar_1    conda-forge
alabaster                 0.7.13             pyhd8ed1ab_0    conda-forge
anyio                     3.6.2              pyhd8ed1ab_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
arb                       2.23.0               he5401aa_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py38hb991d35_3    conda-forge
arpack                    3.7.0                h58ebc17_2    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
backports.zoneinfo        0.2.1            py38hb991d35_7    conda-forge
bdw-gc                    8.0.6                hc021e02_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
beniget                   0.4.1              pyhd8ed1ab_0    conda-forge
blas-devel                3.9.0           16_osxarm64_openblas    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
brial                     1.2.12             pyha3edaa6_0    conda-forge
brotli                    1.0.9                h1a8c8d9_8    conda-forge
brotli-bin                1.0.9                h1a8c8d9_8    conda-forge
brotlipy                  0.7.0           py38hb991d35_1005    conda-forge
bwidget                   1.9.14               hce30654_1    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.18.1               h3422bc3_0    conda-forge
ca-certificates           2022.12.7            h4653dfc_0    conda-forge
cairo                     1.16.0            h73a0509_1014    conda-forge
cctools_osx-arm64         973.0.1             hef52d2f_13    conda-forge
cddlib                    1!0.94m              h6d7a090_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py38ha45ccd6_3    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
clang                     14.0.6               hce30654_0    conda-forge
clang-14                  14.0.6          default_h81a5282_0    conda-forge
clang_osx-arm64           14.0.6               h15773ab_6    conda-forge
clangxx                   14.0.6          default_hb7ecf47_0    conda-forge
clangxx_osx-arm64         14.0.6               he29aa18_6    conda-forge
cliquer                   1.22                 h27ca646_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.3              pyhd8ed1ab_0    conda-forge
compiler-rt               14.0.6               h30b49de_0    conda-forge
compiler-rt_osx-arm64     14.0.6               h48302dc_0    conda-forge
contourpy                 1.0.7            py38h9dc3d6a_0    conda-forge
cryptography              40.0.1           py38h23f6d3d_0    conda-forge
curl                      7.88.1               h9049daf_1    conda-forge
cvxopt                    1.3.0            py38hd15c5c0_4    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cypari2                   2.1.3            py38h18f8f8f_1    conda-forge
cysignals                 1.11.2           py38h57b977d_1    conda-forge
cython                    0.29.34          py38h2b1e499_0    conda-forge
debugpy                   1.6.7            py38h2b1e499_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
docutils                  0.19             py38h10201cd_1    conda-forge
dsdp                      5.8               h9397a75_1203    conda-forge
ecl                       21.2.1               h8492d4d_2    conda-forge
eclib                     20221012             h099c6ef_1    conda-forge
ecm                       7.0.4             h47c7c1a_1002    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hb7217d7_1    conda-forge
fflas-ffpack              2.4.3                h11f2abc_2    conda-forge
fftw                      3.3.10          nompi_h3046061_107    conda-forge
flintqs                   1.0               ha2e105b_1001    conda-forge
flit-core                 3.8.0              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h82840c6_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.39.3           py38hb991d35_0    conda-forge
fplll                     5.4.4                h29209e0_0    conda-forge
fpylll                    0.5.9            py38hfed99dd_0    conda-forge
freetype                  2.12.1               hd633e50_1    conda-forge
fribidi                   1.0.10               h27ca646_0    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gap-core                  4.11.1               he8f4e70_5    conda-forge
gap-defaults              4.11.1               hce30654_5    conda-forge
gast                      0.5.3              pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               h0186832_0    conda-forge
gf2x                      1.3.0                hdaa854c_2    conda-forge
gfan                      0.6.2             hec08f5c_1003    conda-forge
gfortran_impl_osx-arm64   11.3.0              h2a9d086_31    conda-forge
gfortran_osx-arm64        11.3.0               h57527a5_1    conda-forge
giac                      1.9.0.21             h1c96721_1    conda-forge
giflib                    5.2.1                h1a8c8d9_3    conda-forge
givaro                    4.1.1                h76d1151_2    conda-forge
glpk                      5.0                  h6d7a090_0    conda-forge
gmp                       6.2.1                h9f76cd9_0    conda-forge
gmpy2                     2.1.2            py38h904d018_1    conda-forge
graphite2                 1.3.13            h9f76cd9_1001    conda-forge
gsl                       2.7                  h6e638da_0    conda-forge
harfbuzz                  6.0.0                hddbc195_0    conda-forge
icu                       70.1                 h6b3803e_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
igraph                    0.9.10               hcec9b84_1    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
iml                       1.0.5             hd52f0d1_1003    conda-forge
importlib-metadata        6.2.0              pyha770c72_0    conda-forge
importlib-resources       5.12.0             pyhd8ed1ab_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
ipykernel                 6.22.0             pyh736e0ef_0    conda-forge
ipython                   8.12.0             pyhd1c38e8_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                8.0.6              pyhd8ed1ab_0    conda-forge
isl                       0.25                 h9a09cb3_0    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jmol                      14.32.10             hce30654_0    conda-forge
jpeg                      9e                   h1a8c8d9_3    conda-forge
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter_client            7.4.9              pyhd8ed1ab_0    conda-forge
jupyter_core              4.12.0           py38h10201cd_0    conda-forge
jupyter_events            0.6.3              pyhd8ed1ab_0    conda-forge
jupyter_server            2.5.0              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.7              pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.4            py38h9dc3d6a_1    conda-forge
krb5                      1.20.1               h69eda48_0    conda-forge
lcalc                     2.0.5                hc94e8e6_1    conda-forge
lcms2                     2.15                 h481adae_0    conda-forge
ld64_osx-arm64            609                 h7167370_13    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libblas                   3.9.0           16_osxarm64_openblas    conda-forge
libbraiding               1.1                  h9f76cd9_0    conda-forge
libbrial                  1.2.12               he94e455_0    conda-forge
libbrotlicommon           1.0.9                h1a8c8d9_8    conda-forge
libbrotlidec              1.0.9                h1a8c8d9_8    conda-forge
libbrotlienc              1.0.9                h1a8c8d9_8    conda-forge
libcblas                  3.9.0           16_osxarm64_openblas    conda-forge
libclang-cpp14            14.0.6          default_h81a5282_0    conda-forge
libcurl                   7.88.1               h9049daf_1    conda-forge
libcxx                    16.0.1               h75e25f2_0    conda-forge
libdeflate                1.17                 h1a8c8d9_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libflint                  2.9.0           h173eafc_ntl_100    conda-forge
libgd                     2.3.3                h90fb8ed_4    conda-forge
libgfortran               5.0.0           12_2_0_hd922786_31    conda-forge
libgfortran-devel_osx-arm64 11.3.0              hfe9555d_31    conda-forge
libgfortran5              12.2.0              h0eea778_31    conda-forge
libglib                   2.74.1               h4646484_1    conda-forge
libhomfly                 1.02r6               h27ca646_0    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
liblapack                 3.9.0           16_osxarm64_openblas    conda-forge
liblapacke                3.9.0           16_osxarm64_openblas    conda-forge
libllvm14                 14.0.6               hf6e71e7_1    conda-forge
libnghttp2                1.52.0               hae82a92_0    conda-forge
libopenblas               0.3.21          openmp_hc731615_3    conda-forge
libpng                    1.6.39               h76d750c_0    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libsqlite                 3.40.0               h76d750c_0    conda-forge
libssh2                   1.10.0               h7a5bd25_3    conda-forge
libtiff                   4.5.0                h5dffbdd_2    conda-forge
libwebp                   1.2.4                h999c80f_1    conda-forge
libwebp-base              1.2.4                h1a8c8d9_0    conda-forge
libxcb                    1.13              h9b22ae9_1004    conda-forge
libxml2                   2.10.3               h67585b2_4    conda-forge
libzlib                   1.2.13               h03a7124_4    conda-forge
linbox                    1.6.3                h549c411_7    conda-forge
llvm-openmp               16.0.1               h7cfbb63_0    conda-forge
llvm-tools                14.0.6               hf6e71e7_1    conda-forge
lrcalc                    2.1                  hb7217d7_4    conda-forge
m4ri                      20140914          h17b34a0_1005    conda-forge
m4rie                     20150908          h17b34a0_1001    conda-forge
make                      4.3                  he57ea6c_1    conda-forge
markupsafe                2.1.2            py38hb991d35_0    conda-forge
matplotlib-base           3.7.1            py38hbbe890c_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
maxima                    5.45.0               h6032a66_2    conda-forge
memory-allocator          0.1.2            py38hb991d35_2    conda-forge
metis                     5.1.0             h9f76cd9_1006    conda-forge
mistune                   2.0.5              pyhd8ed1ab_0    conda-forge
mpc                       1.3.1                h91ba8db_0    conda-forge
mpfi                      1.5.4             hbde5f5b_1001    conda-forge
mpfr                      4.2.0                he09a6ba_0    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nauty                     2.7.2                h3422bc3_0    conda-forge
nbclassic                 0.5.5              pyhb4ecaf3_1    conda-forge
nbclient                  0.7.3              pyhd8ed1ab_0    conda-forge
nbconvert                 7.3.0              pyhd8ed1ab_2    conda-forge
nbconvert-core            7.3.0              pyhd8ed1ab_2    conda-forge
nbconvert-pandoc          7.3.0              pyhd8ed1ab_2    conda-forge
nbformat                  5.8.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
networkx                  2.8.8              pyhd8ed1ab_0    conda-forge
notebook                  6.5.4              pyha770c72_0    conda-forge
notebook-shim             0.2.2              pyhd8ed1ab_0    conda-forge
ntl                       11.4.3               hbb3f309_1    conda-forge
numpy                     1.24.2           py38hac8ee1c_0    conda-forge
openblas                  0.3.21          openmp_hf78f355_3    conda-forge
openjdk                   17.0.3               hf913c23_6    conda-forge
openjpeg                  2.5.0                hbc2ba62_2    conda-forge
openssl                   3.1.0                h03a7124_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
palp                      2.20                 h27ca646_0    conda-forge
pandoc                    2.19.2               hce30654_2    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
pango                     1.50.14              h6c112b8_0    conda-forge
pari                      2.15.3          hee76a8e_2_pthread    conda-forge
pari-galdata              0.0.20180411                  0    conda-forge
pari-seadata-small        0.0.20090618                  0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hb34f9b4_0    conda-forge
perl                      5.32.1          2_h9b22ae9_perl5    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.4.0            py38h1bb68ce_1    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h27ca646_0    conda-forge
pkg-config                0.29.2            hab62308_1008    conda-forge
pkgconfig                 1.5.5              pyhd8ed1ab_4    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
planarity                 3.0.0.5           h27ca646_1002    conda-forge
platformdirs              3.2.0              pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
ppl                       1.2               h8b147cf_1006    conda-forge
pplpy                     0.8.6            py38h544d4bf_1    conda-forge
primecount                7.4                  h2e04ded_1    conda-forge
primecountpy              0.1.0            py38h7b951d2_2    conda-forge
primesieve                8.0                  h9a09cb3_0    conda-forge
prometheus_client         0.16.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
psutil                    5.9.4            py38hb991d35_0    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.14.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyrsistent                0.19.3           py38hb991d35_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.8.16          h3ba56d0_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.3             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-lrcalc             2.1              py38h2b1e499_4    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.8                      3_cp38    conda-forge
pythran                   0.12.1           py38he0a633c_0    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pytz-deprecation-shim     0.1.0.post0      py38h10201cd_3    conda-forge
pyyaml                    6.0              py38hb991d35_5    conda-forge
pyzmq                     24.0.1           py38hb72be9f_1    conda-forge
qd                        2.3.22            hbec66e7_1004    conda-forge
r-base                    4.2.3                heabe65b_0    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
requests                  2.28.2             pyhd8ed1ab_1    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rpy2                      3.5.10          py38r42hb39dbe9_0    conda-forge
rubiks                    20070912          h9f76cd9_1001    conda-forge
rw                        0.9                  h3422bc3_0    conda-forge
sage                      9.8                  hd8ed1ab_0    conda-forge
sage-docbuild             9.8                      pypi_0    pypi
sage-setup                9.8                      pypi_0    pypi
sagelib                   9.8              py38h494b33e_2    conda-forge
sagemath-db-combinatorial-designs 20140630                      1    conda-forge
sagemath-db-conway-polynomials 0.5.0                h4653dfc_1    conda-forge
sagemath-db-elliptic-curves 0.8.1                hecc5488_0    conda-forge
sagemath-db-graphs        20210214             hd8ed1ab_0    conda-forge
sagemath-db-polytopes     20170220                      1    conda-forge
sagemath-standard         9.8                      pypi_0    pypi
sagetex                   3.6.1              pyhd8ed1ab_0    conda-forge
scipy                     1.10.1           py38h7b4f323_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                67.6.1             pyhd8ed1ab_0    conda-forge
sigtool                   0.1.3                h44b9a77_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singular                  4.2.1.p3             hb77faed_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sphinx                    5.3.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
sqlite                    3.40.0               h2229b38_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
suitesparse               5.10.1               h7cd81ec_1    conda-forge
symmetrica                3.0.1                hb7217d7_0    conda-forge
sympow                    2.023.6              hb0babe8_3    conda-forge
sympy                     1.11.1          pypyh9d50eac_103    conda-forge
tachyon                   0.99b6            hfb72b2a_1001    conda-forge
tapi                      1100.0.11            he4954df_0    conda-forge
tbb                       2021.8.0             hffc8910_0    conda-forge
terminado                 0.17.1             pyhd1c38e8_0    conda-forge
three.js                  122                  hd8ed1ab_2    conda-forge
threejs-sage              122                  hd8ed1ab_2    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
tktable                   2.10                 h4161312_3    conda-forge
tornado                   6.2              py38hb991d35_1    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
tzlocal                   4.3              py38h10201cd_0    conda-forge
unicodedata2              15.0.0           py38hb991d35_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.5.1              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.7              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h27ca646_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xsimd                     8.0.5                hc021e02_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
zeromq                    4.3.4                hbdafb3b_1    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h03a7124_4    conda-forge
zn_poly                   0.9.2                h391046e_0    conda-forge
zstd                      1.5.2                hf913c23_6    conda-forge
```

### Environment info

```shell
conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=arm64
                          __osx=12.6=0
                          __unix=0=0
```

**Comment by startakovsky** [comment]
Even after updating mamba / conda all of these commands say the package is not found 

https://anaconda.org/conda-forge/libgap

conda install -c conda-forge libgap
conda install -c "conda-forge/label/cf201901" libgap
conda install -c "conda-forge/label/cf202003" libgap
conda install -c "conda-forge/label/gcc7" libgap

**Comment by startakovsky** [comment]
```Looking for: ['libgap']

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.8.*


Could not solve for environment specs
The following package could not be installed
└─ libgap   does not exist (perhaps a typo or a missing channel).```

**Comment by alexjbest** [comment]
What is the original import error, perhaps this is fixed by https://github.com/sagemath/sage/pull/35351 (I'm actually not sure if the libgap conda package is needed by sage at all these days, it seems very out of date at any rate)

**Comment by startakovsky** [comment]
@alexjbest 

```Python 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:13)
[Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from sage.combinat.tableau import Tableau
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/steven/.pyenv/versions/mambaforge/envs/big-macs-llm/lib/python3.8/site-packages/sage/combinat/tableau.py", line 107, in <module>
    from sage.combinat import permutation
  File "/Users/steven/.pyenv/versions/mambaforge/envs/big-macs-llm/lib/python3.8/site-packages/sage/combinat/permutation.py", line 252, in <module>
    from sage.libs.gap.libgap import libgap
  File "sage/libs/gap/libgap.pyx", line 1, in init sage.libs.gap.libgap (build/cythonized/sage/libs/gap/libgap.c:9039)
  File "sage/libs/gap/util.pyx", line 1, in init sage.libs.gap.util (build/cythonized/sage/libs/gap/util.c:9321)
  File "sage/libs/gap/element.pyx", line 1, in init sage.libs.gap.element (build/cythonized/sage/libs/gap/element.c:29374)
  File "sage/groups/perm_gps/permgroup_element.pyx", line 129, in init sage.groups.perm_gps.permgroup_element (build/cythonized/sage/groups/perm_gps/permgroup_element.c:25328)
ImportError: cannot import name libgap
>>>```

**Comment by startakovsky** [comment]
@alexjbest The recommendation to do `mamba install gap` did not solve this issue, even though it ended up installing these: 

```bliss                                              111.4kB @   1.2MB/s  0.1s
antic                                               56.9kB @ 606.7kB/s  0.1s
eigen                                                1.3MB @  10.0MB/s  0.1s
libsemigroups                                      984.6kB @   6.0MB/s  0.1s
libeantic                                          148.7kB @ 773.3kB/s  0.2s
normaliz                                             5.2MB @  19.3MB/s  0.1s
fmt                                                171.1kB @ 567.8kB/s  0.3s
gap                                                283.2MB @  42.5MB/s  6.6s```

**Comment by startakovsky** [comment]
I just tried to do this with anaconda too... 



```
>>> from sage.combinat.tableau import Tableau
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/steven/.pyenv/versions/anaconda3-2023.03/envs/big-macs-llm/lib/python3.10/site-packages/sage/combinat/tableau.py", line 107, in <module>
    from sage.combinat import permutation
  File "/Users/steven/.pyenv/versions/anaconda3-2023.03/envs/big-macs-llm/lib/python3.10/site-packages/sage/combinat/permutation.py", line 252, in <module>
    from sage.libs.gap.libgap import libgap
  File "sage/libs/gap/libgap.pyx", line 1, in init sage.libs.gap.libgap (build/cythonized/sage/libs/gap/libgap.c:9039)
  File "sage/libs/gap/util.pyx", line 1, in init sage.libs.gap.util (build/cythonized/sage/libs/gap/util.c:9321)
  File "sage/libs/gap/element.pyx", line 1, in init sage.libs.gap.element (build/cythonized/sage/libs/gap/element.c:29374)
  File "sage/groups/perm_gps/permgroup_element.pyx", line 129, in init sage.groups.perm_gps.permgroup_element (build/cythonized/sage/groups/perm_gps/permgroup_element.c:25328)
ImportError: cannot import name libgap
>>>```


The steps I followed are standard, I think: 

```
0. Install Homebrew
0. brew update
0. `brew install pyenv`
0. `pyenv install anaconda-2023.03`
0.  `pyenv local anaconda-2023.03`
0.  Delete the ~/.condarc file
0.  conda config --add channels conda-forge
0.  conda config --set channel_priority strict
0.  conda install mamba
0.  mamba create -n new_env sage python=3.10
0.  conda activate new_env
```

**Comment by startakovsky** [comment]
@alexjbest Do you think it could be because the libgap file is a pyx file and that that requires other libraries that Anaconda cannot handle?

**Comment by startakovsky** [comment]
OK at this point I tried with the instructions here: https://doc.sagemath.org/html/en/installation/conda.html#sec-installation-conda

anaconda-2023.03 installed sage but the sage cli is not working and the import that requires the libgap.pyx file is not working.

Of all the installation options conda was most appealing because it was the first instruction that allowed me to separate out the other parts of the sage install.... seems the best path forward for now is to do what I want to do on the sage docker container. Let me know if you come up with any advice on this...

**Comment by alexjbest** [comment]
Does your conda installed gap work ok? (e.g. can you run gap from the command line and do non-trivial things with it?)
It looks like you have an M2 mac, is that the case? (If so I'm not super surprised that some parts don't quite work to be honest, as far as I know we dont have any testing for such a set up @saraedum )

**Comment by isuruf** [comment]
@startakovsky, sage needs to import files in a specific order as there are lots of cyclic import involved.
Try
```
import sage.all
from sage.combinat.tableau import Tableau
```

**Comment by startakovsky** [comment]
Hey @alexjbest I do have an M1 mac. Yes this import no longer errors out. @isuruf this worked great, I have it all working for this. I am about to open up another ticket though, related to the sage cli not working. I will reference this ticket to get a sense of my set up. I am happy to not go with Docker and to stay simple with conda. Thank you.

<img width="741" alt="image" src="https://user-images.githubusercontent.com/689723/231031317-bb221178-3a76-41d6-8d65-4cf6fcfba733.png">
